jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dotnet: [ '3.1.100' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
